version: '3.7'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: localhost
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: camerashop
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: admin
      PMA_PASSWORD: admin
    ports:
      - 8306:80

